version: '3'

services:
    client:
        build:
            context: ./client
        container_name: client
        volumes:
            - ./client:/usr/app
        ports:
            - 3000:3000
    api:
        build:
            context: ./api
        container_name: api
        volumes:
            - ./api:/usr/app
        ports:
            - 3001:3000
