version: '3'

services:
    client:
        build:
            context: ./client
        container_name: client
        volumes:
            - ./client:/usr/app
        ports:
            - 3000:3000
        networks:
            - connection
    api:
        build:
            context: ./api
        container_name: api
        volumes:
            - ./api:/usr/app
        ports:
            - 3001:3000
        networks:
            - connection
    db:
        image: mongo:5.0
        container_name: db
        volumes:
            - ./db:/data/db
        ports:
            - 27017:27017
        networks:
            - connection

networks:
    connection:
        driver: bridge
