version: '3'

services:
    client:
        build:
            context: ./client
        container_name: client
        volumes:
            - ./client:/usr/app
        ports:
            - 3000:3000
